# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: de094920d2cdc5b88710122b4307a72a7fae10c791ee0f998f4b04155e0d5b79f7c33bbd143e2d0ef2395e77ebaa81445a17ece22c3525fce2a1a16affcb1981

test:
  secret_key_base: cd12188126400e5e40b10f0700530b0c7bf0a91511ffc45725d15496c43c427f4484101566340ff1a078de01cbc4f655a187dd4ee80277e5266bbdd695eccd29

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
